ros cpp demo with better comments

diff --git a/ci_example_cpp/demos/ci_example_ros_demo b/ci_example_cpp/demos/ci_example_ros_demo
--- a/ci_example_cpp/demos/ci_example_ros_demo
+++ b/ci_example_cpp/demos/ci_example_ros_demo
@@ -3,6 +3,8 @@
 ### this scripts expects ci_example_ros binary to be in ./bin folder
 ### this binary is compiled and copied there during install. See CMakeLists.txt for details
 
+
+# trying to start ros, exiting with error code if fail
 source /opt/ros/groovy/setup.bash 
 roscore &
 sleep 2
@@ -10,22 +12,31 @@ roscore_running=$(ps aux | grep roscore | grep opt)
 if [ -z "$roscore_running" ]
 then
     echo "failed to start roscore"
-else
-    
-    echo "------ setting parameters -----"
-    rosparam set gains_kp 1
-    rosparam set gains_kd 1
-    rosparam set gains_ki 1
-
-    echo ""
-    echo "------ CPP DEMO START ------"
-    echo ""
-    ./bin/ci_example_ros
-    echo ""
-    echo "------ DEMO END ------"
-    echo ""
-
-
-pkill roscore
+    exit 1
 fi
+
+# setting parameters in ros parameter server    
+echo "------ setting parameters -----"
+rosparam set gains_kp 1
+rosparam set gains_kd 1
+rosparam set gains_ki 1
+
+
+# if the next commands return error code, stopping roscore and exiting with error message
+# if not implemented, the continuous integration script will not know the demo failed 
+# (because ci_example_ros will return an error code, but not this script)
+trap "pkill roscore && exit 1" ERR EXIT
+
+# running the demo
+echo ""
+echo "------ CPP DEMO START ------"
+echo ""
+./bin/ci_example_ros
+echo ""
+echo "------ DEMO END ------"
+echo ""
+
+# stopping ros
+pkill roscore
+
 
