python and cpp demos using deferred exit code instead of trap

diff --git a/ci_example_python/demos/ci_example_ros_demo b/ci_example_python/demos/ci_example_ros_demo
--- a/ci_example_python/demos/ci_example_ros_demo
+++ b/ci_example_python/demos/ci_example_ros_demo
@@ -34,7 +34,7 @@ echo ""
 echo "------ PYTHON DEMO START ------"
 echo ""
 python ./src/ci_example_python_ros_demo.py 
-success = $?
+success=$? # $? is the exit code of the latest command, here call to python
 echo ""
 echo "------ DEMO END ------"
 echo ""
